#web_routes:
#    resource:
#        path: ../../Presentation/Web
#        namespace: Site\Partner\Presentation\Web
#    type: attribute

api_routes:
  resource:
    path: ../../Presentation/Api
    namespace: Profile\User\Presentation\Api
  type: attribute
  prefix: '/api'