parameters:
    validation_routes:
        - 'register'
        - 'forgot-password'
        - 'login'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
           $validationRoutes: '%validation_routes%'

    App\Shared\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../DomainModel/Event/'
            - '../../DomainModel/Model/'
            - '../../Tests/'

    # Define the HTTP client service
    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    Psr\Http\Client\ClientInterface: '@GuzzleHttp\Client'

    GuzzleHttp\Psr7\HttpFactory:
        class: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\RequestFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    Psr\Http\Message\UriFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'

    # Global Assert Validation Error Handler
    App\Shared\Infrastructure\ErrorHandler\GlobalErrorHandler:
        tags:
            - { name: kernel.event_subscriber }

    App\Shared\Presentation\Responder\JsonResponder:
        tags:
            - { name: kernel.event_subscriber }

    App\Shared\Presentation\Responder\HtmlResponder:
        tags:
            - { name: kernel.event_subscriber }