doctrine:
    dbal:
        connections:
            site:
                url: '%env(resolve:DATABASE_SITE_URL)%'
        types:
            user_id: Site\User\Infrastructure\Doctrine\DoctrineType\UserIdType
            user_status: Site\User\Infrastructure\Doctrine\DoctrineType\UserStatusType
    orm:
        entity_managers:
            site:
                connection: site
                mappings:
                    User:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Site/User/DomainModel/Model'
                        prefix: 'Site\User\DomainModel\Model'
                        alias: User