doctrine:
    dbal:
        types:
            user_status_id: Profile\UserStatus\Infrastructure\Persistence\Doctrine\Type\UserStatusIdType
        connections:
            site:
                url: '%env(resolve:DATABASE_SITE_URL)%'
            services:
                url: '%env(resolve:DATABASE_SERVICES_URL)%'
            orders:
                url: '%env(resolve:DATABASE_ORDERS_URL)%'
    orm:
        entity_managers:
            site:
                connection: site
                mappings:
                    Setting:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Profile/UserStatus/DomainModel/Model'
                        prefix: 'Profile\UserStatus\DomainModel\Model'
                        alias: Setting