parameters:
    is_online_ttl: 300 # 5 minutes

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $isOnlineTtl: '%is_online_ttl%'

    Profile\UserStatus\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Application/**/*{Command,Query}.php'
            - '../../DomainModel/{Dto,Event,Model,ValueObject}/'
            - '../../Application/*/{Dto,Event,Model,ValueObject}/'
            - '../../Tests/'
        tags: ['controller.service_arguments']

    Profile\UserStatus\Infrastructure\Persistence\Doctrine\Repository\UserStatusRepository:
        arguments:
            $entityManager: '@doctrine.orm.site_entity_manager'

    Profile\UserStatus\DomainModel\Repository\UserStatusRepositoryInterface:
        alias: UserStatus\Infrastructure\Persistence\Doctrine\Repository\UserStatusRepository

    # EventSubscriber
    Profile\UserStatus\DomainModel\EventSubscriber\UserActivitySubscriber:
        tags:
            - { name: kernel.event_subscriber }
