#doctrine:
#    orm:
#        mappings:
#            Service:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Services/DomainModel/Model'
#                prefix: 'Services\DomainModel\Model'
#                alias: Service