parameters:
    app_host: '%env(APP_HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Services\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../DomainModel/Model/'
            - '../../Tests/'
            - '../../**/Tests/'
        tags: ['controller.service_arguments']