parameters:
    default_currency: '%env(DEFAULT_CURRENCY)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $defaultCurrency: '%default_currency%'

    Services\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../DomainModel/Model/'
            - '../../Tests/'
            - '../../**/Tests/'
        tags: ['controller.service_arguments']