parameters:
    app.name: 'EasyOrder'
    app.host: '%env(APP_HOST)%'
    app.support_email: 'support@easyorder.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'