parameters:
    app.mailer.from: '%env(MAILER_FROM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Shared\Infrastructure\Notification\Transport\CustomEmailTransport:
        arguments:
            $mailer: '@mailer.mailer'

    custom-email:
        class: App\Shared\Infrastructure\Notification\Channel\CustomEmailChannel
        arguments:
            $transport: '@App\Shared\Infrastructure\Notification\Transport\CustomEmailTransport'
        tags: ['notifier.channel']
