parameters:
    api_geo_host: '%env(API_GEO_HOST)%'
    api_geo_user_name: '%env(API_GEO_USER_NAME)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiGeoHost: '%api_geo_host%'
            $apiGeoUserName: '%api_geo_user_name%'

    App\Registration\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Presentation/**/Response'
            - '../../Presentation/**/Response'
            - '../../Application/**/*Command.php'
            - '../../Application/**/*Query.php'
            - '../../DomainModel/Event/'
            - '../../DomainModel/Model/'
            - '../../Tests/'
        tags: ['controller.service_arguments']

    # Services
    App\Shared\Presentation\Responder\ResponderInterface: '@App\Registration\Infrastructure\Clients\GeoNamesClient'
    
    App\Registration\Infrastructure\Clients\GeoNamesClient:
        arguments:
            $client: '@Psr\Http\Client\ClientInterface'
            $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
            $uriFactory: '@Psr\Http\Message\UriFactoryInterface'

twig:
    paths:
        '%kernel.project_dir%/src/Registration/Resources/Templates': Registration