parameters:
    supported_countries: '%env(json:SUPPORTED_COUNTRIES)%'
    password_secret_key: '%env(PASSWORD_SECRET_KEY)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $passwordSecretKey: '%password_secret_key%'
            $supportedCountries: '%supported_countries%'
            $noCaptchaEnabled: '%nocaptcha.enabled%'

    App\Registration\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Presentation/**/Response'
            - '../../Application/**/*{Command,Query}.php'
            - '../../DomainModel/{Dto,Event,Model,ValueObject}/'
            - '../../Application/*/{Dto,Event,Model,ValueObject}/'
            - '../../Tests/'
        tags: ['controller.service_arguments']

    App\Registration\Presentation\Web\Twig\RegistrationExtension:
        tags: ['twig.extension']

twig:
    paths:
        '%kernel.project_dir%/src/Registration/Resources/Templates': Registration