parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Registration\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../DomainModel/Model/'
            - '../../Tests/'
            - '../../**/Tests/'
        tags: ['controller.service_arguments']

twig:
    paths:
        '%kernel.project_dir%/src/Registration/Resources/Templates': Registration