parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Registration\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Application/**/*Command.php'
            - '../../Application/**/*Query.php'
            - '../../DomainModel/Event/'
            - '../../DomainModel/Model/'
            - '../../Tests/'
        tags: ['controller.service_arguments']

twig:
    paths:
        '%kernel.project_dir%/src/Registration/Resources/Templates': Registration