global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php:9000']

  - job_name: 'php-app'
    static_configs:
      - targets: ['php:8080']
    metrics_path: '/metrics'

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
