parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Notification\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Presentation/**/Response'
            - '../../Application/**/*{Command,Query}.php'
            - '../../DomainModel/{Dto,Event,Model,ValueObject}/'
            - '../../Application/*/{Dto,Event,Model,ValueObject}/'
            - '../../Tests/'
        tags: ['controller.service_arguments']

#    Notification\Infrastructure\Repository\EventRepository:
#        arguments:
#            $entityManager: '@doctrine.orm.site_entity_manager'
#
#    Notification\DomainModel\Repository\EventRepositoryInterface:
#        alias: Notification\Infrastructure\Repository\EventRepository