parameters:

twig:
    paths:
        '%kernel.project_dir%/src/Notification/Resources/Templates': Notifications

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Notification\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Application/**/*{Command,Query}.php'
            - '../../DomainModel/{Dto,Event,Model,ValueObject}/'
            - '../../Application/*/{Dto,Event,Model,ValueObject}/'
            - '../../Tests/'
        tags: ['controller.service_arguments']

    Notification\Infrastructure\Repository\UserNotificationRepository:
        arguments:
            $entityManager: '@doctrine.orm.site_entity_manager'

    Notification\DomainModel\Repository\UserNotificationRepositoryInterface:
        alias: Notification\Infrastructure\Repository\UserNotificationRepository