doctrine:
    dbal:
        types:
            client_id: App\Client\Infrastructure\Doctrine\DoctrineType\ClientIdType
            client_status: App\Client\Infrastructure\Doctrine\DoctrineType\ClientStatusType
        connections:
            client:
                url: '%env(resolve:DATABASE_CLIENT_URL)%'
    orm:
        entity_managers:
            client:
                connection: client
                mappings:
                    Client:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Client/DomainModel/Model'
                        prefix: 'App\Client\DomainModel\Model'
                        alias: Client