doctrine:
    orm:
        entity_managers:
            client:
                connection: client
                mappings:
                    Client:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Client/DomainModel/Model'
                        prefix: 'App\Client\DomainModel\Model'
                        alias: Client