doctrine:
    dbal:
        default_connection: client
        connections:
            client:
                url: '%env(resolve:DATABASE_CLIENT_URL)%'
    orm:
        default_entity_manager: client
        entity_managers:
            client:
                connection: client
                mappings:
                    Client:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Client/DomainModel/Model'
                        prefix: 'App\Client\DomainModel\Model'
                        alias: Client