security:
    password_hashers:
        App\Client\DomainModel\Model\Client: 'auto'

    providers:
        client_provider:
            entity:
                class: App\Client\DomainModel\Model\Client
                property: email
                manager_name: client
