parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Client\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../DomainModel/Model/'
            - '../../Tests/'
            - '../../**/Tests/'
        tags: ['controller.service_arguments']

    App\Client\Infrastructure\Repository\ClientRepository:
        arguments:
            $entityManager: '@doctrine.orm.client_entity_manager'

    App\Client\DomainModel\Repository\ClientRepositoryInterface:
        alias: App\Client\Infrastructure\Repository\ClientRepository