openapi: 3.0.0
info:
  title: 'Enterprise Skeleton API'
  version: 1.0.0
paths:
  /api/test:
    get:
      tags:
        - Test
      summary: 'Test route message'
      operationId: 563b292f621ded0a96c6774840eaf5d3
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
              example: Test
tags:
  -
    name: Test
    description: Test
