parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Healthcheck\:
        resource: '../../'
        exclude:
            - '../../Resources/'
        tags: ['controller.service_arguments']

    App\Healthcheck\Presentation\Console\MysqlHealthcheckCommand:
        arguments:
            $clientDatabaseUrl: '%env(DATABASE_CLIENT_URL)%'
            $partnerDatabaseUrl: '%env(DATABASE_PARTNER_URL)%'