framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - src/Site/Locale/Resources/Assets/
            - src/Site/Location/Resources/Assets/
            - src/Site/Dashboard/Resources/Assets/
            - src/Site/Registration/Resources/Assets/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
