framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - src/Locale/Resources/assets/
            - src/Dashboard/Resources/assets/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
