imports:
    - { resource: '../../src/Shared/Resources/Config/doctrine.yaml' }
    - { resource: '../../src/Location/Resources/Config/doctrine.yaml' }
    - { resource: '../../src/Partner/Resources/Config/doctrine.yaml' }
    - { resource: '../../src/Client/Resources/Config/doctrine.yaml' }

doctrine:
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
