# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write
    # from it. Remove or comment this line if you want to manage sessions by yourself.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    
    assets:
        enabled: true
        json_manifest_path: null

when@prod:
    framework:
        assets:
            version: '%env(APP_VERSION)%'
            version_strategy: null

when@dev:
    framework:
        assets:
            version: null
            version_strategy: App\Dashboard\Infrastructure\Asset\TimestampVersionStrategy

when@test:
    framework:
        test: true
        http_method_override: true
        session:
            storage_factory_id: session.storage.factory.mock_file
