# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write
    # from it. Remove or comment this line if you want to manage sessions by yourself.
    session:
        handler_id: redis.session.handler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    
    assets:
        enabled: true

when@prod:
    framework:
        assets:
            version: '%env(APP_VERSION)%'

        error_controller: App\Dashboard\Presentation\Web\ExceptionAction
        exceptions:
            Symfony\Component\HttpKernel\Exception\NotFoundHttpException:
                log_level: error
                status_code: 404
            Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException:
                log_level: error
                status_code: 403
            Symfony\Component\HttpKernel\Exception\HttpException:
                log_level: error
                status_code: 500

when@test:
    framework:
        test: true
        http_method_override: true
        session:
            storage_factory_id: session.storage.factory.mock_file
