knpu_oauth2_client:
  clients:
    facebook:
      type: facebook
      client_id: '%env(FACEBOOK_APP_ID)%'
      client_secret: '%env(FACEBOOK_APP_SECRET)%'
      redirect_route: connect_facebook_check
      graph_api_version: 'v12.0' # Актуальная версия API
