framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus: ~
            event.bus: ~

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'in-memory://default'

        routing:
            Site\Registration\DomainModel\Event\UserLoggedInEvent: sync
            Site\Registration\DomainModel\Event\UserRegisteredEvent: sync
