parameters:
    nocaptcha.enabled: true

services:
    Anhskohbo\NoCaptcha\NoCaptcha:
        arguments:
            $secret: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
            $sitekey: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

when@dev:
    parameters:
        nocaptcha.enabled: false
