imports:
    - { resource: '../../src/Profile/User/Resources/Config/security.yaml' }

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        all_users:
            chain:
#                providers: ['site_provider', 'orders_provider', 'services_provider']
                providers: ['site_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            custom_authenticator:
                - Site\Registration\Infrastructure\Security\UserLoginAuthenticator
                - Site\Registration\Infrastructure\Security\FacebookAuthenticator
                - Site\Registration\Infrastructure\Security\GoogleAuthenticator
            entry_point: Site\Registration\Infrastructure\Security\FacebookAuthenticator
            logout:
                path: logout
                target: dashboard
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/notifications, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/v1/users, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/v1/settings, roles: PUBLIC_ACCESS, methods: [GET]  }
        - { path: ^/api/v1/settings, roles: [ROLE_PARTNER,ROLE_CLIENT], methods: [POST, PUT, DELETE] }
        - { path: ^/settings, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/profile, roles: [ROLE_PARTNER,ROLE_CLIENT] }
        - { path: ^/favorites, roles: [ROLE_PARTNER,ROLE_CLIENT] }
        - { path: ^/notifications, roles: [ROLE_PARTNER,ROLE_CLIENT] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
