security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Partner\DomainModel\Model\Partner: 'auto'
        App\Client\DomainModel\Model\Client: 'auto'

    providers:
        partner_provider:
            entity:
                class: App\Partner\DomainModel\Model\Partner
                property: email
                manager_name: partner
        client_provider:
            entity:
                class: App\Client\DomainModel\Model\Client
                property: email
                manager_name: client
        all_users:
            chain:
                providers: ['partner_provider', 'client_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: dashboard_page
            logout:
                path: app_logout
                target: dashboard_page
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/partner, roles: ROLE_PARTNER }
        - { path: ^/client, roles: ROLE_CLIENT }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
