imports:
    - { resource: '../../src/Partner/Resources/Config/security.yaml' }
    - { resource: '../../src/Client/Resources/Config/security.yaml' }

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        all_users:
            chain:
                providers: ['partner_provider', 'client_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            custom_authenticator:
                - App\Registration\Infrastructure\Security\UserLoginAuthenticator
            logout:
                path: logout
                target: dashboard
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset_password, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/partner, roles: ROLE_PARTNER }
        - { path: ^/client, roles: ROLE_CLIENT }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
