#web_routes:
#    resource:
#        path: ../../Presentation/Web
#        namespace: App\Service\Presentation\Web
#    type: attribute

api_routes:
    resource:
        path: ../../Presentation/Api
        namespace: App\Service\Presentation\Api
    type: attribute
    prefix: '/api'