web_routes:
    resource:
        path: ../../Presentation/Web
        namespace: Notifications\Presentation\Web
    type: attribute

api_routes:
    resource:
        path: ../../Presentation/Api
        namespace: Notifications\Presentation\Api
    type: attribute
    prefix: '/api'