doctrine:
    dbal:
        default_connection: partner
        connections:
            partner:
                url: '%env(resolve:DATABASE_PARTNER_URL)%'
    orm:
        default_entity_manager: partner
        entity_managers:
            partner:
                connection: partner
                mappings:
                    Partner:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Partner/DomainModel/Model'
                        prefix: 'App\Partner\DomainModel\Model'
                        alias: Partner