doctrine:
    dbal:
        types:
            property_category: Site\Setting\Infrastructure\Doctrine\DoctrineType\PropertyCategoryType
            property_name: Site\Setting\Infrastructure\Doctrine\DoctrineType\PropertyNameType
            setting_id: Site\Setting\Infrastructure\Doctrine\DoctrineType\SettingIdType
        connections:
            site:
                url: '%env(resolve:DATABASE_SITE_URL)%'
            services:
                url: '%env(resolve:DATABASE_SERVICES_URL)%'
            orders:
                url: '%env(resolve:DATABASE_ORDERS_URL)%'
    orm:
        entity_managers:
            site:
                connection: site
                mappings:
                    Setting:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Site/Setting/DomainModel/Model'
                        prefix: 'Site\Setting\DomainModel\Model'
                        alias: Setting