web_routes:
    resource:
        path: ../../Presentation/Web
        namespace: Site\Setting\Presentation\Web
    type: attribute

api_routes:
    resource:
        path: ../../Presentation/Api
        namespace: Site\Setting\Presentation\Api
    type: attribute
    prefix: '/api'