parameters:

twig:
    paths:
        '%kernel.project_dir%/src/Site/Setting/Resources/Templates': Setting

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Site\Setting\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Application/**/*{Command,Query}.php'
            - '../../DomainModel/{Dto,Event,Model,ValueObject}/'
            - '../../Application/*/{Dto,Event,Model,ValueObject}/'
            - '../../Tests/'
        tags: ['controller.service_arguments']

    Site\Setting\Infrastructure\Repository\SettingRepository:
        arguments:
            $entityManager: '@doctrine.orm.site_entity_manager'

    Site\Setting\DomainModel\Repository\SettingRepositoryInterface:
        alias: Site\Setting\Infrastructure\Repository\SettingRepository